### ISSUE TITLE
Doctype

### ISSUE THREAD

**Issue by grupohernandezalba** [CuanaloIbarraDaniel/6.-Georeferienciados#1]
Hola @CuanaloIbarraDaniel solo te falto poner bien la etiqueta del Doctype, solo con que le pongas el caracter **<** , ya con eso va estar bien.

![Captura de Pantalla 2020-02-19 a la(s) 13 19 27](https://user-images.githubusercontent.com/14998558/74867599-90b11180-531a-11ea-9e9f-1eaec08498d0.png)

**Comment by CuanaloIbarraDaniel** [comment]
El índice ha sido actualizado para resolver este problema.
