### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by grupohernandezalba** [CuanaloIbarraDaniel/6.-Georeferienciados#3]
Muy bien @CuanaloIbarraDaniel trata solo de darle mas margen a los botones que no te queden tan cercanos uno del otro para que el usuario no se equivoque.

![Captura de Pantalla 2020-03-12 a la(s) 21 29 26](https://user-images.githubusercontent.com/14998558/76587189-b4deb900-64a8-11ea-9107-363ee25e8ce9.png)

**Comment by CuanaloIbarraDaniel** [comment]
Se han realizado las correcciones necesarias.
